import { User } from "src/app/interfaces/user.ts";

export const users : User[] = [
    {
        businessPhones: ['123456789'],
        displayName: 'Amit Kumar',
        givenName: 'Amit',
        jobTitle: 'Software Engineer',
        mail: 'amit.kumar@example.com',
        mobilePhone: '9876543210',
        officeLocation: 'Bangalore',
        preferredLanguage: 'en-US',
        surname: 'Kumar',
        userPrincipalName: 'amit.kumar@example.com',
        id: '1'
    },
    {
        businessPhones: ['987654321'],
        displayName: 'Rajesh Patel',
        givenName: 'Rajesh',
        jobTitle: 'Product Manager',
        mail: 'rajesh.patel@example.com',
        mobilePhone: '8765432109',
        officeLocation: 'Mumbai',
        preferredLanguage: 'en-IN',
        surname: 'Patel',
        userPrincipalName: 'rajesh.patel@example.com',
        id: '2'
    },
    {
        businessPhones: ['234567890'],
        displayName: 'Sneha Gupta',
        givenName: 'Sneha',
        jobTitle: 'Marketing Manager',
        mail: 'sneha.gupta@example.com',
        mobilePhone: '7654321098',
        officeLocation: 'New Delhi',
        preferredLanguage: 'en-IN',
        surname: 'Gupta',
        userPrincipalName: 'sneha.gupta@example.com',
        id: '3'
    },
    {
        businessPhones: ['345678901'],
        displayName: 'Anjali Singh',
        givenName: 'Anjali',
        jobTitle: 'HR Executive',
        mail: 'anjali.singh@example.com',
        mobilePhone: '6543210987',
        officeLocation: 'Pune',
        preferredLanguage: 'en-IN',
        surname: 'Singh',
        userPrincipalName: 'anjali.singh@example.com',
        id: '4'
    },
    {
        businessPhones: ['456789012'],
        displayName: 'Deepak Sharma',
        givenName: 'Deepak',
        jobTitle: 'Finance Analyst',
        mail: 'deepak.sharma@example.com',
        mobilePhone: '5432109876',
        officeLocation: 'Chennai',
        preferredLanguage: 'en-IN',
        surname: 'Sharma',
        userPrincipalName: 'deepak.sharma@example.com',
        id: '5'
    },
    {
        businessPhones: ['567890123'],
        displayName: 'Pooja Mishra',
        givenName: 'Pooja',
        jobTitle: 'UI Designer',
        mail: 'pooja.mishra@example.com',
        mobilePhone: '4321098765',
        officeLocation: 'Hyderabad',
        preferredLanguage: 'en-IN',
        surname: 'Mishra',
        userPrincipalName: 'pooja.mishra@example.com',
        id: '6'
    },
    {
        businessPhones: ['678901234'],
        displayName: 'Manoj Reddy',
        givenName: 'Manoj',
        jobTitle: 'Project Manager',
        mail: 'manoj.reddy@example.com',
        mobilePhone: '3210987654',
        officeLocation: 'Kolkata',
        preferredLanguage: 'en-IN',
        surname: 'Reddy',
        userPrincipalName: 'manoj.reddy@example.com',
        id: '7'
    },
    {
        businessPhones: ['789012345'],
        displayName: 'Priya Nair',
        givenName: 'Priya',
        jobTitle: 'HR Manager',
        mail: 'priya.nair@example.com',
        mobilePhone: '2109876543',
        officeLocation: 'Ahmedabad',
        preferredLanguage: 'en-IN',
        surname: 'Nair',
        userPrincipalName: 'priya.nair@example.com',
        id: '8'
    },
    {
        businessPhones: ['890123456'],
        displayName: 'Rahul Verma',
        givenName: 'Rahul',
        jobTitle: 'Sales Executive',
        mail: 'rahul.verma@example.com',
        mobilePhone: '1098765432',
        officeLocation: 'Jaipur',
        preferredLanguage: 'en-IN',
        surname: 'Verma',
        userPrincipalName: 'rahul.verma@example.com',
        id: '9'
    },
    {
        businessPhones: ['901234567'],
        displayName: 'Sunita Jain',
        givenName: 'Sunita',
        jobTitle: 'Product Designer',
        mail: 'sunita.jain@example.com',
        mobilePhone: '0987654321',
        officeLocation: 'Lucknow',
        preferredLanguage: 'en-IN',
        surname: 'Jain',
        userPrincipalName: 'sunita.jain@example.com',
        id: '10'
    },
    {
        businessPhones: ['123456789'],
        displayName: 'Amit Kumar',
        givenName: 'Amit',
        jobTitle: 'Software Engineer',
        mail: 'amit.kumar@example.com',
        mobilePhone: '9876543210',
        officeLocation: 'Bangalore',
        preferredLanguage: 'en-US',
        surname: 'Kumar',
        userPrincipalName: 'amit.kumar@example.com',
        id: '1'
    },
    {
        businessPhones: ['987654321'],
        displayName: 'Rajesh Patel',
        givenName: 'Rajesh',
        jobTitle: 'Product Manager',
        mail: 'rajesh.patel@example.com',
        mobilePhone: '8765432109',
        officeLocation: 'Mumbai',
        preferredLanguage: 'en-IN',
        surname: 'Patel',
        userPrincipalName: 'rajesh.patel@example.com',
        id: '2'
    },
    {
        businessPhones: ['234567890'],
        displayName: 'Sneha Gupta',
        givenName: 'Sneha',
        jobTitle: 'Marketing Manager',
        mail: 'sneha.gupta@example.com',
        mobilePhone: '7654321098',
        officeLocation: 'New Delhi',
        preferredLanguage: 'en-IN',
        surname: 'Gupta',
        userPrincipalName: 'sneha.gupta@example.com',
        id: '3'
    },
    {
        businessPhones: ['345678901'],
        displayName: 'Anjali Singh',
        givenName: 'Anjali',
        jobTitle: 'HR Executive',
        mail: 'anjali.singh@example.com',
        mobilePhone: '6543210987',
        officeLocation: 'Pune',
        preferredLanguage: 'en-IN',
        surname: 'Singh',
        userPrincipalName: 'anjali.singh@example.com',
        id: '4'
    },
    {
        businessPhones: ['456789012'],
        displayName: 'Deepak Sharma',
        givenName: 'Deepak',
        jobTitle: 'Finance Analyst',
        mail: 'deepak.sharma@example.com',
        mobilePhone: '5432109876',
        officeLocation: 'Chennai',
        preferredLanguage: 'en-IN',
        surname: 'Sharma',
        userPrincipalName: 'deepak.sharma@example.com',
        id: '5'
    },
    {
        businessPhones: ['567890123'],
        displayName: 'Pooja Mishra',
        givenName: 'Pooja',
        jobTitle: 'UI Designer',
        mail: 'pooja.mishra@example.com',
        mobilePhone: '4321098765',
        officeLocation: 'Hyderabad',
        preferredLanguage: 'en-IN',
        surname: 'Mishra',
        userPrincipalName: 'pooja.mishra@example.com',
        id: '6'
    },
    {
        businessPhones: ['678901234'],
        displayName: 'Manoj Reddy',
        givenName: 'Manoj',
        jobTitle: 'Project Manager',
        mail: 'manoj.reddy@example.com',
        mobilePhone: '3210987654',
        officeLocation: 'Kolkata',
        preferredLanguage: 'en-IN',
        surname: 'Reddy',
        userPrincipalName: 'manoj.reddy@example.com',
        id: '7'
    },
    {
        businessPhones: ['789012345'],
        displayName: 'Priya Nair',
        givenName: 'Priya',
        jobTitle: 'HR Manager',
        mail: 'priya.nair@example.com',
        mobilePhone: '2109876543',
        officeLocation: 'Ahmedabad',
        preferredLanguage: 'en-IN',
        surname: 'Nair',
        userPrincipalName: 'priya.nair@example.com',
        id: '8'
    },
    {
        businessPhones: ['890123456'],
        displayName: 'Rahul Verma',
        givenName: 'Rahul',
        jobTitle: 'Sales Executive',
        mail: 'rahul.verma@example.com',
        mobilePhone: '1098765432',
        officeLocation: 'Jaipur',
        preferredLanguage: 'en-IN',
        surname: 'Verma',
        userPrincipalName: 'rahul.verma@example.com',
        id: '9'
    },
    {
        businessPhones: ['901234567'],
        displayName: 'Sunita Jain',
        givenName: 'Sunita',
        jobTitle: 'Product Designer',
        mail: 'sunita.jain@example.com',
        mobilePhone: '0987654321',
        officeLocation: 'Lucknow',
        preferredLanguage: 'en-IN',
        surname: 'Jain',
        userPrincipalName: 'sunita.jain@example.com',
        id: '10'
    },
    {
        businessPhones: ['012345678'],
        displayName: 'Ravi Kumar',
        givenName: 'Ravi',
        jobTitle: 'Software Developer',
        mail: 'ravi.kumar@example.com',
        mobilePhone: '9876543210',
        officeLocation: 'Bangalore',
        preferredLanguage: 'en-IN',
        surname: 'Kumar',
        userPrincipalName: 'ravi.kumar@example.com',
        id: '11'
    },
    {
        businessPhones: ['123456780'],
        displayName: 'Kavita Sharma',
        givenName: 'Kavita',
        jobTitle: 'Project Manager',
        mail: 'kavita.sharma@example.com',
        mobilePhone: '8765432109',
        officeLocation: 'Mumbai',
        preferredLanguage: 'en-IN',
        surname: 'Sharma',
        userPrincipalName: 'kavita.sharma@example.com',
        id: '12'
    },
    {
        businessPhones: ['234567801'],
        displayName: 'Sanjay Gupta',
        givenName: 'Sanjay',
        jobTitle: 'Sales Manager',
        mail: 'sanjay.gupta@example.com',
        mobilePhone: '7654321098',
        officeLocation: 'New Delhi',
        preferredLanguage: 'en-IN',
        surname: 'Gupta',
        userPrincipalName: 'sanjay.gupta@example.com',
        id: '13'
    },
    {
        businessPhones: ['345678912'],
        displayName: 'Divya Singh',
        givenName: 'Divya',
        jobTitle: 'Software Engineer',
        mail: 'divya.singh@example.com',
        mobilePhone: '6543210987',
        officeLocation: 'Pune',
        preferredLanguage: 'en-IN',
        surname: 'Singh',
        userPrincipalName: 'divya.singh@example.com',
        id: '14'
    },
    {
        businessPhones: ['456789123'],
        displayName: 'Rakesh Kumar',
        givenName: 'Rakesh',
        jobTitle: 'Marketing Executive',
        mail: 'rakesh.kumar@example.com',
        mobilePhone: '5432109876',
        officeLocation: 'Chennai',
        preferredLanguage: 'en-IN',
        surname: 'Kumar',
        userPrincipalName: 'rakesh.kumar@example.com',
        id: '15'
    },
];


