name: Notify Teams Channel

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.webhook_secret }}
        run: |
          python .github/workflows/script.py '${{toJson(github.event)}}' > /dev/null 2>&1 | curl -X POST -H "Content-Type: application/json" -d @- $TEAMS_WEBHOOK_URL
