name: Notify Teams Channel

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.webhook_secret }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "A new push has been made to the main branch. Details: Commit ID: ${{ github.sha }}, Commit Message: ${{ github.event.head_commit.message }}"
          }' $TEAMS_WEBHOOK_URL
          run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "A new push has been made to the main branch. Details: Commit ID: ${{ github.sha }}", "git_event": ${{ toJson(github.event)}}
          }' https://7528-121-241-162-10.ngrok-free.app/curl-check

        


        
