name: Notify Teams Channel

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.webhook_secret }}
          GITHUB_EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          python .github/workflows/script.py "${{GITHUB_EVENT_PAYLOAD}}" | curl -X POST -H "Content-Type: application/json" -d @- $TEAMS_WEBHOOK_URL
